---
title: "Organize important data from a gene coexpression network"
author: "AustinTHilliard"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: workflowr::wflow_html
---
  
## Setup
### Clean workspace, set options, load functions
```{r start clean and source functions}
rm(list=ls())
options(stringsAsFactors=FALSE)
library(WGCNA)

# source other code, some of which requires WGNCA functions
source("code/organize_coexpression_network_functions.R")
```
<!--#### Some functions in [.R](https://github.com/AustinTHilliard/networks/blob/master/code/.R) are from the [WGNCA library (version 1.63)](https://cran.r-project.org/web/packages/WGCNA/index.html). I included them here rather than require you to install WGCNA-->

### Load and prepare data
#### Load expression data and output from WGCNA::blockwiseModules
```{r load data}
# males_6ASC_7D_6ND_0var_medtpm.5_.33zeros_log2_preProc-dev2.5-IAC2_batch-lib-tank-seqdate_replace-negs/
load("data/DATAfilt_signed_p18_ds4_mm100_mch0.2_mKME0.3_mCoreKME0.5run57DATA.RData")
load("data/DATAfilt_signed_p18_ds4_mm100_mch0.2_mKME0.3_mCoreKME0.5run57NET.RData")
ls()
dim(DATA)
DATA[1:5, 1:5]
sapply(net,length)
```

#### Generate important network objects
<!--This function will save network objects into the workspace (dendro, blockGenes, colors, MEs), compute kME for every gene-ME pair (kME), create a list of vectors holding genes assigned to each module (modGenes), and create a list of data frames holding kME and p.kME for genes in each module (modkMEs)-->
```{r getNetworkBasics}
.getNetworkBasics(net, DATA, "")
ls()
# dendro and blockGenes are mostly just used for plotting.
# if there is only one network block, re-save the dendrogram and set blockGenes to NULL.
if (length(blockGenes) == 1) {
  dendro = dendro[[1]]
  blockGenes = NULL
} 
dendro
blockGenes

# colors is a vector where each entry represents the module assignment for a gene.
#  It's ordered the same as the columns of the expression data (DATA)
#   i.e., colors[n] is the module of the gene represented by DATA[, n], and length(colors) should equal ncol(DATA).
length(colors)
sort(table(colors))

# MEs is a matrix where each column is a module eigengene (ME), ordered by how correlated they are, and ncol(MEs) should equal length(unique(colors)).
#  The row order corresponds to the samples represented by the rows of DATA
#   i.e., MEs[m, n] is the PC1 loading for the nth module on sample DATA[m, ].
dim(MEs)
MEs[1:5, 1:5]

# kME is a data frame where each row is a gene and the columns represent the correlations (with p-values) to MEs.
#  nrow(kMEs) should equal ncol(DATA), but the genes may not be ordered the same, and ncol(kMEs) should equal 2*ncol(MEs).
dim(kME)
kME[1:5, 1:5]
```